[project]
name = "schenker"
version = "0.1.0"
description = "DB Schenker scraper"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "beautifulsoup4>=4.14.3",
    "fastmcp>=2.14.0",
    "logging>=0.4.9.6",
    "playwright>=1.57.0",
]
